# Generated by Django 5.1.7 on 2025-05-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_choice', models.CharField(max_length=10)),
                ('computer_choice', models.CharField(max_length=10)),
                ('result', models.CharField(max_length=20)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
